services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realtime-monitoring-postgresql
    volumes:
      - ".:/app"
    env_file:
      - .env.local
    tty: true
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env.db
    container_name: realtime-monitoring-postgresql-db
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    ports:
      - "5433:5432"